/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Validated { 'completed' : boolean, 'description' : string }
export interface ValidatedInput {
  'id' : bigint,
  'completed' : boolean,
  'description' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTodo' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteTodo' : ActorMethod<[bigint], undefined>,
  'editTodo' : ActorMethod<[bigint, string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [string]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTodo' : ActorMethod<[bigint], [] | [Validated]>,
  'getTodos' : ActorMethod<[], [] | [Array<ValidatedInput>]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [string]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRegistered' : ActorMethod<[], boolean>,
  'signUp' : ActorMethod<[string], undefined>,
  'toggleTodo' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];